### ISSUE TITLE
Modified datetime is incorrectly parsed

### ISSUE THREAD

**Issue by izh1** [hgupta9/FluentFTP#13]
Hi!

Trying to figure out the modification time of the file in the directory.
The modification time of the directory shows correctly (debug values):

> Created = {01.01.0001 0:00:00}
> FullName = "/73/6878398845"
> Input = "drwxrwxr-x    2 ftp      ftp          4096 Nov 24 12:30 6878398845"
> Modified = {24.11.2016 12:30:00}
> 

....
Next, try to know the modification time of the file in this directory (debug values):

> Created = {01.01.0001 0:00:00}
> Input = "-rw-rw-r--    1 ftp      ftp        392872 Nov 24 12:30 AKT VYPOLNENNYH RABOT(1).PDF"
> Modified = {24.11.2016 16:30:33}

Why is not the same as the Modified time and Input params (12:30 -is real local time, 16:30 - converted to UTC. I have to convert back ) ?
At the same time, the directory everything is fine.

```
var items = ftp.GetListing(ftpUri.Uri.LocalPath, FtpListOption.ForceList | FtpListOption.Modify);
                foreach(var item in items)
                {
                    if (item.Type != FtpFileSystemObjectType.Directory)
                        continue;

                    var files = ftp.GetListing(item.FullName, FtpListOption.ForceList | FtpListOption.Modify);
               }
```

**Comment by izh1** [comment]
when will solved this problem, some additional data needed?

**Comment by k2ace** [comment]
I'm also seeing issues with modify times.  It doesn't seem to be handling year correctly, December of prior year is coming across as December of current year.  The actual modify date is 1 Dec 2016 but is coming across as 1 Dec 2017.

Modified: 12/1/2017 10:45:00 PM
Input: -rw-r--r--   1 fxx      fxx     748 Dec  1 22:45 tt2011216224500.log

**Comment by izh1** [comment]
These example appears to be following the same standard as the UNIXy ls -l command, which only shows the year for dates older than six months.

If that's the case, you could infer the year easily but you should be aware that the format isn't guaranteed, it probably depends on the underlying OS the FTP server is running on.

Please implement this in FluentFtp

**Comment by hgupta9** [comment]
As you can see in the input string, the year is not specified. Date/time parsing is very hard since there is no standard, and differs from server to server. If you can tell me what part of the string is the year, that data can probably be read into the date object.

> Modified: 12/1/2017 10:45:00 PM
> Input: -rw-r--r-- 1 fxx fxx 748 **Dec 1** 22:45 tt2011216224500.log

**Comment by hgupta9** [comment]
@izh1 
I don't know what Trosclair implemented for time conversion. AFAIK its just reading the data into an object. More research will be needed to see if any UTC conversion is happening.

**Comment by izh1** [comment]
@hgupta9 
I figured out,, I incorrectly entered FtpListOption.
FTP server support  MLSD | SIZE | MDTM | REST | UTF8 | MFMT.
If you specify `GetListing(item, FtpListOption.ForceList | FtpListOption.Modify);` then FluentFTP use ` LIST` command. 
Here is the correct version: `GetListing(item, FtpListOption.Modify);` - result directory and file modified time in UTC time - is correct.

Up to this point did not penetrate to the standard FTP, I did not know that different approaches to determine the date and time.

**Comment by k2ace** [comment]
@hgupta9 
It's a unix system so it's using POSIX logic below.  The only other platform I have ran across that does this is NetWare, which is the same logic using 12 month rules instead of 6.  

For the current issue I was having I have altered the script generating the files to inject a timestamp the file named and altered my processing code to use this instead of modify time.

If would be nice if the client detected the host during connection (SYST command maybe) or had a way to specify the host type or some other way to control date parsing/conversion logic.

POSIX logic.
https://www.gnu.org/software/coreutils/manual/html_node/Formatting-file-timestamps.html

Another good reference more related directly to ftp LIST output is ftpparse: 
http://cr.yp.to/ftpparse.html

**Comment by hgupta9** [comment]
@izh1 - Thanks for the tip,  I added your findings to the readme.

**Comment by hgupta9** [comment]
@h2ace - Does the SYST command help detect if the host is POSIX?

**Comment by k2ace** [comment]
@hgupta9 
Yes,  on the three FTP servers I noticed the issue with dates they are all unix/sunos.  The response from SYST on all three since they are all the same base platform.  The exact response I see is:
215 UNIX Type: L8 Version: SUNOS

**Comment by hgupta9** [comment]
I've upgraded the GetListing() file listing parser to include OS-specific parsers. This may resolve your issue. If you are interested in helping debug this, then please use this beta build and give me feedback: 

- [FluentFTP_16.6_BETA.rar](https://we.tl/YiWHrDYJxq)

**Comment by hgupta9** [comment]
This issue should be fixed in 16.6 and onwards. If its not, please reply here and I'll reopen the issue.

**Comment by FetFlex** [comment]
I just tried out FluentFTP and i am seeing this on a UNIX FTP server but not a Windows FTP. I can see that the info is in Listing:
Listing:  modify=20170712090021;perm=flcdmpe;type=dir;unique=8A0U1040334FC;UNIX.group=1203;UNIX.mode=0755;UNIX.owner=1200; files

But when i try to get the Created it just says: 01-01-0001 00:00:00

I tried setting the FtpListOption.Modify. It does not seem to have worked. If i used it correctly:
foreach (FtpListItem item in client.GetListing(@"\", FtpListOption.Modify))

What am i doing wrong?

**Comment by A9G-Data-Droid** [comment]
@FetFlex I ran in to this today. It still doesn't work 100% here 3 years later on the latest version. I found you can manually pull the correct information using `client.GetModifiedTime(item.FullName)`

I made my code optionally check again if the time looks blank:

```
var lastModified = item.Modified
If (lastModified.ToString("HH:mm:ss") = "00:00:00")
    lastModified = client.GetModifiedTime(item.FullName)
```

_I leave this here because this came up on google before I found my solution._
