### ISSUE TITLE
Listing does not work when working directory path contains spaces

### ISSUE THREAD

**Issue by masdomas** [hgupta9/FluentFTP#63]
Getting an exception when trying to list items in a directory:

`client.GetListing("newfolder");`

```
FluentFTP.FtpCommandException : Invalid number of arguments MLSD /apps/custom/some data/users/newfolder

   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
```

I think that's because working directory path contains space (directory "some data"). 

I've tried all FtpListingFlags but nothing helped.

Thanks

**Comment by hgupta9** [comment]
Can you try `GetListing("/apps/custom/some+data/users/newfolder")` and see if that works?

**Comment by hgupta9** [comment]
Similar to https://github.com/hgupta9/FluentFTP/issues/27

**Comment by masdomas** [comment]
Still does not work:

```
FluentFTP.FtpCommandException : Invalid number of arguments MLSD /apps/custom/some data/users/apps/custom/some+data/users/newfolder

   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
```

**Comment by hgupta9** [comment]
Thats because your working directory is something else. Don't change your working directory and try again. Or do:

    SetWorkingDirectory("/")
    GetListing("/apps/custom/some+data/users/newfolder")

**Comment by masdomas** [comment]
Sorry, I do not have permission to change working directory, I guess it is set upon login.

When I tried the suggested code:

`FluentFTP.FtpCommandException : Permission denied`

**Comment by hgupta9** [comment]
Then just try executing a raw command `Execute("MSLD /apps/custom/some+data/users/newfolder")` and see if it works?

**Comment by masdomas** [comment]
This gives a different error. However, it is no longer complaining about two arguments.

```
550
Command MLSD failed
```

**Comment by hgupta9** [comment]
I tried looking this up to no avail. 

The error code 550 means "Access is denied"

**Comment by hgupta9** [comment]
This is the format of the command

> MLSD [SP pathname]

where `SP` means special flags, and `pathname` is the dir - both optional args.

**Comment by hgupta9** [comment]
Try this:

    Execute("CWD /apps/custom/some+data/users/newfolder/")
    Execute("MLSD")

**Comment by hgupta9** [comment]
Or this

    Execute("CWD /apps/custom/some+data/users/newfolder/")
    Execute("TYPE A")
    Execute("PASV")
    Execute("MLSD")

**Comment by masdomas** [comment]
Interesting... 

Execute("CWD /apps/custom/some+data/users/newfolder/") didn't work, but 
Execute("CWD /apps/custom/some data/users/newfolder/") did work

Execute("TYPE A") executed immediately (success)
Execute("PASV") executed immediately (success)

Execute("MLSD") took 10 minutes to run even though there are only 157 files in that folder and returned an empty ReplyReply object (no status, no message), exception was not thrown

**Comment by hgupta9** [comment]
Thanks for the reply. I'll try debugging it tomorrow.

**Comment by hgupta9** [comment]
I've upgraded the GetListing() file listing parser to include OS-specific parsers. This may resolve your issue. If you are interested in helping debug this, then please use this beta build and give me feedback: 

- [FluentFTP_16.6_BETA.rar](https://we.tl/YiWHrDYJxq)

**Comment by hgupta9** [comment]
All new features are released on nuget : https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
Closing this since no response received from OP, and is mostly fixed with new GetListing()

**Comment by masdomas** [comment]
Sorry for the late response...

Same issue still occurs in the latest version.

Cloned the code, then modified FluentFTP.FtpExtensions.GetFtpPath(string) by adding line (at line 31):

`path = '"' + path + '"';`

And GetListing(string) method worked as expected. So the problem appears to be in the part where request is sent to the server - paths containing spaces have to be wrapped in double quotes...

**Comment by masdomas** [comment]
By the way, SYST command response is just "UNIX" (no type information, such as L8, etc.)

**Comment by hgupta9** [comment]
Good find. I'll try to incorporate your code into the trunk.

**Comment by masdomas** [comment]
However, I think this might be server dependent - I tested this change with other FTP server (UNIX Type L8), and I think listing stopped working because of the change (returned no files when listed non-empty folder).

**Comment by hgupta9** [comment]
I'm closing this because its server-specific and there is no way to fix it for your server because it simply says UNIX in the syst string.
